/*
 * Copyright (c) 2021 Karnak Team and other contributors.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License 2.0 which is available at http://www.eclipse.org/legal/epl-2.0, or the Apache
 * License, Version 2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 */
package org.karnak.backend.util;

import static org.karnak.backend.enums.ExternalIDProviderType.*;

import org.junit.Assert;
import org.junit.jupiter.api.Test;

class ExternalIDProviderUtilTest {
  @Test
  void getType() {
    Assert.assertEquals(
        ID_GENERATED_BY_MAINZELLISTE,
        ExternalIDProviderUtil.getType("Pseudonym is generated by mainzelliste"));
    Assert.assertEquals(
        EXTID_IN_MAINTELLISTE,
        ExternalIDProviderUtil.getType(
            "Pseudonym that has already been entered manually in mainzelliste"));
    Assert.assertEquals(
        EXTID_IN_CACHE, ExternalIDProviderUtil.getType("Pseudonym is already store in KARNAK"));
    Assert.assertEquals(
        EXTID_IN_TAG, ExternalIDProviderUtil.getType("Pseudonym is in a DICOM tag"));
  }
}
