package org.karnak.backend.enums;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Assert;
import org.junit.jupiter.api.Test;

class ExternalIDProviderTypeTest {

  @Test
  void shouldRetrieveDescription() {
    Assert.assertEquals(
        "Pseudonym is generated by mainzelliste",
        ExternalIDProviderType.ID_GENERATED_BY_MAINZELLISTE.getDescription());
    Assert.assertEquals(
        "Pseudonym that has already been entered manually in mainzelliste",
        ExternalIDProviderType.EXTID_IN_MAINTELLISTE.getDescription());
    Assert.assertEquals(
        "Pseudonym is already store in KARNAK",
        ExternalIDProviderType.EXTID_IN_CACHE.getDescription());
    Assert.assertEquals(
        "Pseudonym is in a DICOM tag",
        ExternalIDProviderType.EXTID_IN_TAG.getDescription());
    Assert.assertEquals(
        "",
        ExternalIDProviderType.EXTID_PROVIDER_IMPLEMENTATION.getDescription());
  }

  @Test
  void shouldRetrieveIsByDefault() {
    Assert.assertTrue(ExternalIDProviderType.ID_GENERATED_BY_MAINZELLISTE.isByDefault());
    Assert.assertTrue(ExternalIDProviderType.EXTID_IN_MAINTELLISTE.isByDefault());
    Assert.assertTrue(ExternalIDProviderType.EXTID_IN_CACHE.isByDefault());
    Assert.assertTrue(ExternalIDProviderType.EXTID_IN_TAG.isByDefault());
    Assert.assertFalse(ExternalIDProviderType.EXTID_PROVIDER_IMPLEMENTATION.isByDefault());

  }
}