#  --------------------------------------------------------
#  Karnak Application Profiles
#  --------------------------------------------------------
name: KARNAK-Profile
environment: LOCAL
karnakadmin: ${KARNAK_ADMIN}
karnakpassword: ${KARNAK_PASSWORD}
mainzelliste:
  apikey: '${MAINZELLISTE_API_KEY}'
  serverurl: 'http://${MAINZELLISTE_HOSTNAME}:${MAINZELLISTE_HTTP_PORT}'
  idtypes: '${MAINZELLISTE_ID_TYPES}'
logging:
  level:
    org:
      springframework: INFO
server:
  port: 8081
spring:
  application:
    name: karnak
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: '@activatedProperties@'
  datasource:
    password: ${DB_PASSWORD}
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: ${DB_USER}
    hikari:
      leak-detection-threshold: 0
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 20000
      max-lifetime: 1800000
  mustache:
    check-template-location: false
  jpa:
    hibernate:
      # First time to create the db the value must be: create
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true

---
spring:
  profiles: docker
logstash:
  servers: logstash:9689