#eureka:
#  datacenter: ${DATACENTER:local}
#  instance:
#    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
#    health-check-url-path: /actuator/health
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1
#    prefer-ip-address: false   # forcer l'enregistrement par hostname
#    metadata-map:
#      startup: ${random.int}    #needed to trigger info and endpoint update after restart
#  client:
#    healthcheck:
#      enabled: true
#    register-with-eureka: false
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
#    registry-fetch-interval-seconds: 3
#    region: ${REGION:local}




eureka:
  datacenter: ${DATACENTER:local}
  instance:
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: false   # forcer l'enregistrement par hostname
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    enabled: true
#    healthcheck:
#      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
#      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3
    region: ${REGION:local}


#hazelcast:
#  shouldUseDns: false
#  name: hazelcast-karnak
#  serviceUrl:
#    default: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}