#  --------------------------------------------------------
#  Karnak Docker Application properties
#  --------------------------------------------------------
#Logstash
logstash:
  servers: logstash:9689