#  --------------------------------------------------------
#  Karnak OIDC Application properties
#  --------------------------------------------------------
#Keycloak OIDC
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: '${OIDC_CLIENT_ID:undefined}'
            client-secret: '${OIDC_CLIENT_SECRET:undefined}'
            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri: 'https://karnak-dev.hcuge.ch/login/oauth2/code/{registrationId}'
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: '${OIDC_ISSUER_URI:undefined}'