#  --------------------------------------------------------
#  Karnak Application Profiles
#  --------------------------------------------------------
name: KARNAK-Profile
#environment: LOCAL
karnakadmin: ${KARNAK_ADMIN:admin}
karnakpassword: ${KARNAK_PASSWORD:admin}
mainzelliste:
  apikey: '${MAINZELLISTE_API_KEY:changeThisApiKey}'
  serverurl: 'http://${MAINZELLISTE_HOSTNAME:localhost}:${MAINZELLISTE_HTTP_PORT:8083}'
logging:
  level:
    org:
      springframework: INFO
    com:
      vaadin:
        flow:
          server:
            communication:
              # Suppress WARN  c.v.f.s.c.ReturnChannelHandler - Ignoring update for disabled return channel
              rpc:
                MapSyncRpcHandler: ERROR
              ReturnChannelHandler: ERROR
server:
  port: 8081
  servlet:
    session:
      persistent: false
  forward-headers-strategy: NATIVE
spring:
  application:
    name: karnak
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: '@activatedProperties@,docker,redis, eureka'
  datasource:
    password: ${DB_PASSWORD:5!KAnN@%98%d}
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:karnak}'
    username: ${DB_USER:karnak}
    hikari:
      leak-detection-threshold: 0
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 20000
      max-lifetime: 1800000
  mustache:
    check-template-location: false
  jpa:
    hibernate:
      # First time to create the db the value must be: create
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true

# add info for all microservices
info:
  environment: ${ENVIRONMENT}
  tags:
    eureka.datacenter: ${eureka.datacenter}
    eureka.instance-id: ${eureka.instance.instance-id}
management:
  endpoint:
    health:
      show-details: always
# https://github.com/spring-projects/spring-boot/issues/20509
    env:
      post.enabled: true      
#issue with spring cloud Hoxton.SR10 and sup
    restart:
      enabled: false
    pause:
      enabled: false
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  health:
    config:
      enabled: false
  server:
    port: ${SERVER_MANAGEMENT_PORT:18089}
  info:
    env:
      enabled: true #disabled by default in springboot 2.6
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      percentiles:
        '[http.server.requests]': 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        '[http.server.requests]': 50ms, 150ms, 250ms, 400ms
    tags:
      application: ${spring.application.name}
      instance: ${eureka.instance.instance-id}
      team: ${application.team}

monitoring:
  max-history: 150000
