version: '3.7'

name: karnak

services:
  karnak-db:
    container_name: karnak-db
    image: repo-docker.hcuge.ch:9082/postgres:14.6-alpine3.17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=karnak
      - POSTGRES_USER=karnak
      - POSTGRES_PASSWORD=karnak
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
    secrets:
      - postgres_karnak_password
    networks:
      - karnak-data

  node-dicom:
    image: dcm4che/dcm4che-tools:5.22.6
    entrypoint: [ "storescp", "-b", "NODE:4444", "--directory", "/home/images" ]
    ports:
      - 4444:4444

  karnak-cache:
    image: redis:latest
    ports:
      - 6379:6379
#    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning


secrets:
  karnak_login_password:
    file: secrets/karnak_login_password
  postgres_karnak_password:
    file: secrets/karnak_postgres_password
  oidc_client_secret:
    file: secrets/oidc_client_secret

volumes:
  karnak-db-data:
networks:
  reverseproxy:
  karnak-data: