version: '3.7'

services:
  karnak:
    image: repo-docker.hcuge.ch:9082/karnak:${SERVICE_VERSION}
  #    environment:
  #      JAVA_OPTS: -XX:MaxRAM=512m -XX:MaxRAMPercentage=75 -XX:+UseContainerSupport -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=162M
  #      KARNAK_WAIT_FOR: karnak-db:5432
  #    env_file: karnak.env
  #    depends_on:
  #      - karnak-db

  karnak-db:
    image: repo-docker.hcuge.ch:9082/postgres:hug-9.6-alpine
  #    environment:
  #      - POSTGRES_DB=karnak
  #      - POSTGRES_USER=karnak
  #      - POSTGRES_PASSWORD=H2srmXJbHaBUhBafn2BK5I9oSbaQ1rw8697V8ESs/2o=

  mainzelliste-db:
    image: repo-docker.hcuge.ch:9082/postgres:hug-9.6-alpine
  #    environment:
  #      - POSTGRES_DB=mainzelliste
  #      - POSTGRES_USER=mainzelliste
  #      - POSTGRES_PASSWORD=LCqWpeyJi6uStLdIq98tD+NHvJ+yVYDgOknet5slIIk=

  mainzelliste:
    image: repo-docker.hcuge.ch:9082/osirixfoundation/karnak-mainzelliste:extid
  #    env_file: mainzelliste.env
  #    depends_on:
  #      - mainzelliste-db

  karnak-cache:
    image: repo-docker.hcuge.ch:9082/redis:6.0.16-alpine3.15

  db-backup:
    image: repo-docker.hcuge.ch:9082/pqsql-backup-s3:2.0

  mainzelliste-db-backup:
    image: repo-docker.hcuge.ch:9082/pqsql-backup-s3:2.0