version: '3.7'

services:
  karnak:
    image: repo-docker.hcuge.ch:9082/karnak:${SERVICE_VERSION}

  karnak-db:
    image: repo-docker.hcuge.ch:9082/postgres:hug-13.2-alpine

  mainzelliste-db:
    image: repo-docker.hcuge.ch:9082/postgres:hug-13.2-alpine

  mainzelliste:
    image: repo-docker.hcuge.ch:9082/osirixfoundation/karnak-mainzelliste:extid

  karnak-cache:
    image: repo-docker.hcuge.ch:9082/redis:6.0.16-alpine3.15

  db-backup:
    image: repo-docker.hcuge.ch:9082/pqsql-backup-s3:2.0

  mainzelliste-db-backup:
    image: repo-docker.hcuge.ch:9082/pqsql-backup-s3:2.0