version: '3.7'

services:
  karnak:
    image: registry-docker.hcuge.ch:8083/karnak:1.0.0
    environment:
      JAVA_OPTS: -XX:MaxRAM=512m -XX:MaxRAMPercentage=75 -XX:+UseContainerSupport -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=162M
      KARNAK_WAIT_FOR: karnak-db:5432
    ports:
      - "11112:11119"
      - "13081:8081"
    env_file: karnak.env
    depends_on:
      - karnak-db

  karnak-db:
    image: postgres:12.4-alpine
    ports:
      - ${KARNAK_PG_PORT}:5432
    environment:
      - POSTGRES_DB=karnak
      - POSTGRES_USER=karnak
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_karnak_password

  mainzelliste-db:
    image: registry-docker.hcuge.ch:8083/postgres:9.6-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD_FILE=/run/secrets/mainzellisteDbPassword

  mainzelliste:
    image: osirixfoundation/karnak-mainzelliste:extid
    env_file: mainzelliste.env
    ports:
      - ${MAINZELLISTE_WEB_PORT}:8080
    depends_on:
      - mainzelliste-db
