/*
 * Copyright (c) 2021 Karnak Team and other contributors.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0, or the Apache
 * License, Version 2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 */
package org.karnak.backend.enums;

public enum ExternalIDProviderType {
  ID_GENERATED_BY_MAINZELLISTE("Pseudonym is generated by mainzelliste", true),
  EXTID_IN_MAINTELLISTE("Pseudonym that has already been entered manually in mainzelliste", true),
  EXTID_IN_CACHE("Pseudonym is already store in KARNAK", true),
  EXTID_IN_TAG("Pseudonym is in a DICOM tag", true),
  EXTID_PROVIDER_IMPLEMENTATION("", false);

  private final String description;
  private final boolean byDefault;

  ExternalIDProviderType(String description, boolean byDefault) {
    this.description = description;
    this.byDefault = byDefault;
  }

  public String getDescription() {
    return description;
  }

  public boolean isByDefault() {
    return byDefault;
  }
}
